# Generated by Django 2.1 on 2019-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.IntegerField(default=0, verbose_name='登录状态'),
        ),
    ]
