# Generated by Django 2.1 on 2019-09-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin_token',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='后台头'),
        ),
    ]
