# Generated by Django 2.1 on 2019-08-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='state',
        ),
    ]
