# Generated by Django 2.1 on 2019-09-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_admin_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(default='[]', max_length=40, verbose_name='湖北省内主管城市'),
        ),
    ]
