# Generated by Django 2.1 on 2019-09-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190911_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='area',
            field=models.CharField(default='[]', max_length=40, verbose_name='区域'),
        ),
    ]
