# Generated by Django 2.1 on 2019-08-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_users_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.CharField(default='', max_length=16, verbose_name='用户类型'),
        ),
    ]
