# Generated by Django 2.1 on 2019-10-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190911_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacted',
        ),
        migrations.AddField(
            model_name='contact',
            name='contacted_id',
            field=models.IntegerField(default=0, verbose_name='被联系者id'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='联系者id'),
        ),
    ]
