# Generated by Django 2.1 on 2019-10-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191012_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_peo_id', models.IntegerField(default=0, verbose_name='邀请人id')),
                ('register_peo_id', models.IntegerField(default=0, verbose_name='注册人id')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='日期')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='integration',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
