# Generated by Django 2.1 on 2019-10-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191014_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='t_int',
            field=models.IntegerField(default=0, verbose_name='挑刺积分'),
        ),
        migrations.AddField(
            model_name='users',
            name='y_int',
            field=models.IntegerField(default=0, verbose_name='邀请注册积分'),
        ),
    ]
