# Generated by Django 2.1 on 2019-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190806_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.CharField(default='1565251504.png', max_length=32, verbose_name='头像'),
        ),
    ]
