# Generated by Django 2.1 on 2019-10-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_clockrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteregister',
            name='yq_type',
            field=models.CharField(default='', max_length=8, verbose_name='邀请注册或者邀请付费'),
        ),
    ]
