# Generated by Django 2.1 on 2019-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_inviteregister_yq_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_type',
            field=models.IntegerField(default=1, verbose_name='支付方式'),
        ),
    ]
