# Generated by Django 2.1 on 2019-10-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_orderinfo_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.CharField(default='', max_length=64, verbose_name='时间')),
                ('big_list', models.CharField(default='', max_length=500, verbose_name='大列表')),
            ],
        ),
    ]
