# Generated by Django 2.1 on 2019-08-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190815_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_time',
            field=models.CharField(default='', max_length=32, verbose_name='支付时间'),
        ),
    ]
