# Generated by Django 2.1 on 2019-08-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190815_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='支付时间'),
        ),
    ]
