# Generated by Django 2.1 on 2019-11-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiMing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, verbose_name='名次')),
                ('username', models.CharField(default='', max_length=64, verbose_name='名字')),
                ('act_num', models.FloatField(default=0.0, verbose_name='积分')),
            ],
        ),
    ]
