# Generated by Django 2.1 on 2019-08-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190815_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='用户')),
                ('vip_type', models.CharField(default='', max_length=4, verbose_name='vip类型')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='创建日期')),
            ],
        ),
    ]
