# Generated by Django 2.1 on 2019-11-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_paiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiming',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='id'),
        ),
    ]
