# Generated by Django 2.1 on 2019-11-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_paiming_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, verbose_name='名次')),
                ('username', models.CharField(default='', max_length=64, verbose_name='名字')),
            ],
        ),
    ]
