# Generated by Django 2.1 on 2019-08-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_vipinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipinfo',
            name='state',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
