# Generated by Django 2.1 on 2019-08-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_vipinfo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipinfo',
            name='state',
            field=models.IntegerField(default=0, null=True, verbose_name='状态'),
        ),
    ]
