# Generated by Django 2.1 on 2019-11-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_company_register_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='big_list',
            field=models.TextField(default='', verbose_name='大列表'),
        ),
    ]
