# Generated by Django 2.1 on 2019-08-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_vipinfo_order_sn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VipInfo',
        ),
    ]
