# Generated by Django 2.1 on 2019-11-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20191104_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ranking_company',
            field=models.CharField(default='', max_length=50, verbose_name='公司排名'),
        ),
    ]
