# Generated by Django 2.1 on 2019-08-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_delete_vipinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_time',
            field=models.DateField(auto_now_add=True, verbose_name='支付时间'),
        ),
    ]
