# Generated by Django 2.1 on 2019-11-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20191105_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='y_int',
            field=models.IntegerField(default=0, verbose_name='邀请积分'),
        ),
    ]
