# Generated by Django 2.1 on 2019-08-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_users_is_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='users',
            name='vip',
            field=models.CharField(default='无', max_length=5, verbose_name='vip'),
        ),
    ]
