# Generated by Django 2.1 on 2019-11-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20191106_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=8)),
                ('phone', models.CharField(default='', max_length=16)),
            ],
        ),
    ]
