# Generated by Django 2.1 on 2019-08-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20190817_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='vip',
        ),
        migrations.AddField(
            model_name='users',
            name='vip_num',
            field=models.IntegerField(default=0, verbose_name='vip'),
        ),
    ]
