# Generated by Django 2.1 on 2019-11-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_adminuserchart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='paiming',
            name='rank',
        ),
        migrations.AlterField(
            model_name='company',
            name='register_num',
            field=models.FloatField(default=0.0, verbose_name='注册人数'),
        ),
    ]
