# Generated by Django 2.1 on 2019-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20190817_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipExpire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_time', models.DateField(verbose_name='到期时间')),
                ('user_id', models.IntegerField(default=0, verbose_name='user')),
            ],
        ),
    ]
