# Generated by Django 2.1 on 2019-08-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_vipexpire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipexpire',
            name='expire_time',
            field=models.DateTimeField(verbose_name='到期时间'),
        ),
    ]
