# Generated by Django 2.1 on 2019-08-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20190817_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('release_id', models.IntegerField(default=0, verbose_name='发布id')),
                ('contact', models.IntegerField(default=0, verbose_name='联系我的次数')),
                ('contact_ed', models.IntegerField(default=0, verbose_name='被联系的次数')),
                ('luyou', models.CharField(default='', max_length=32, verbose_name='路由')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
