# Generated by Django 2.1 on 2019-08-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_releaserecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaserecord',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='releaserecord',
            name='contact_ed',
        ),
        migrations.RemoveField(
            model_name='releaserecord',
            name='release_id',
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='land_id',
            field=models.IntegerField(default=0, verbose_name='发布信息id'),
        ),
        migrations.AlterField(
            model_name='releaserecord',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='发布用户id'),
        ),
    ]
