# Generated by Django 2.1 on 2019-08-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20190819_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.CharField(default='', max_length=64, verbose_name='id')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('luyou', models.CharField(default='', max_length=32, verbose_name='路由')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.CharField(default='', max_length=64, verbose_name='id')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('luyou', models.CharField(default='', max_length=32, verbose_name='路由')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Contacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.CharField(default='', max_length=64, verbose_name='id')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('luyou', models.CharField(default='', max_length=32, verbose_name='路由')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Zan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.CharField(default='', max_length=64, verbose_name='id')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('luyou', models.CharField(default='', max_length=32, verbose_name='路由')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
