# Generated by Django 2.1 on 2019-09-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yaoqing',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
