# Generated by Django 2.1 on 2019-08-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigdata',
            name='development_plan',
            field=models.CharField(default='', max_length=256, verbose_name='发展规划'),
        ),
        migrations.AlterField(
            model_name='transinfo',
            name='views_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='查看次数'),
        ),
    ]
