# Generated by Django 2.1 on 2019-09-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_auto_20190916_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YaoQingRead',
        ),
    ]
