# Generated by Django 2.1 on 2019-08-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_auto_20190805_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractinfo',
            name='views_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='查看次数'),
        ),
        migrations.AlterField(
            model_name='investmentdata',
            name='views_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='查看次数'),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='views_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='查看次数'),
        ),
    ]
