# Generated by Django 2.1 on 2019-09-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_delete_yaoqingread'),
    ]

    operations = [
        migrations.CreateModel(
            name='YaoQingRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaoqing_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
