# Generated by Django 2.1 on 2019-08-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_auto_20190805_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingsupplyf',
            name='project_num',
        ),
        migrations.AddField(
            model_name='buildingsupplyf',
            name='year_month',
            field=models.CharField(default=0, max_length=32, verbose_name='年月'),
        ),
    ]
