# Generated by Django 2.1 on 2019-08-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_auto_20190805_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingsupplyt',
            name='project_num',
        ),
        migrations.AddField(
            model_name='buildingsupplyt',
            name='deal_average',
            field=models.FloatField(default=0, verbose_name='成交均价'),
        ),
        migrations.AddField(
            model_name='buildingsupplyt',
            name='year_month',
            field=models.CharField(default='', max_length=32, verbose_name='年月'),
        ),
        migrations.AlterField(
            model_name='buildingsupplyf',
            name='year_month',
            field=models.CharField(default='', max_length=32, verbose_name='年月'),
        ),
    ]
