# Generated by Django 2.1 on 2019-08-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_auto_20190805_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='transferee_peo',
            field=models.CharField(default='', max_length=32, verbose_name='受让人'),
        ),
    ]
