# Generated by Django 2.1 on 2019-10-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_auto_20191012_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='标题'),
        ),
    ]
