# Generated by Django 2.1 on 2019-10-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_auto_20191012_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='编号'),
        ),
    ]
