# Generated by Django 2.1 on 2019-08-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_auto_20190805_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractinfo',
            name='reward_price',
            field=models.IntegerField(default=199, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='reward_price',
            field=models.IntegerField(default=199, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='transinfo',
            name='reward_price',
            field=models.IntegerField(default=199, verbose_name='价格'),
        ),
    ]
