# Generated by Django 2.1 on 2019-10-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_auto_20191012_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='advance_date',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='预告日期'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='building_density',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='建筑密度'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='详细内容'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='deal_money',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='成交金额'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='deal_remark',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='deal_time',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='greening',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='绿化率'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='information_source',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='信息来源'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='is_deal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否成交'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='is_publish',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否已发布'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='land_area',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='用地面积'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='land_nature',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='用地性质'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='listed_date',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='挂牌日期'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='margin',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='保证金'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='plot_ratio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='容积率'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='reward_price',
            field=models.FloatField(blank=True, default=0.01, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='start_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='起始价'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='transfer_date',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='出让日期'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='transfer_mode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='出让方式'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='transferee_peo',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='受让人'),
        ),
    ]
