# Generated by Django 2.1 on 2019-08-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_auto_20190806_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_id', models.CharField(default='', max_length=64, verbose_name='资讯id')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('luyou', models.CharField(default='', max_length=32, verbose_name='路由')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
