# Generated by Django 2.1 on 2019-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0008_universal'),
    ]

    operations = [
        migrations.AddField(
            model_name='universal',
            name='universal_type',
            field=models.IntegerField(default=0, verbose_name='类型'),
        ),
    ]
