# Generated by Django 2.1 on 2019-10-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0009_auto_20191012_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='add_amplitude',
            field=models.CharField(default='', max_length=32, verbose_name='加价幅度'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='deal_money',
            field=models.FloatField(default=0, verbose_name='成交金额'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='now_progress',
            field=models.CharField(default='', max_length=128, verbose_name='目前进度'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='special_requirements',
            field=models.CharField(default='', max_length=256, verbose_name='特殊要求'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='yuji_guapai',
            field=models.CharField(default='', max_length=128, verbose_name='预计挂牌时间'),
        ),
    ]
