# Generated by Django 2.1 on 2019-08-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0010_remove_universal_universal_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Universal',
            new_name='Collection',
        ),
    ]
