# Generated by Django 2.1 on 2019-10-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0013_auto_20191014_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractinfo',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='详细内容'),
        ),
        migrations.AlterField(
            model_name='attractinfo',
            name='cooperate_condition',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='合作条件'),
        ),
        migrations.AlterField(
            model_name='attractinfo',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='attractinfo',
            name='img',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='attractinfo',
            name='img_list',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='图集'),
        ),
        migrations.AlterField(
            model_name='attractinfo',
            name='industry_requirements',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='产业要求'),
        ),
        migrations.AlterField(
            model_name='attractinfo',
            name='information_source',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='信息来源'),
        ),
        migrations.AlterField(
            model_name='attractinfo',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='attractinfo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='transinfo',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='详细内容'),
        ),
        migrations.AlterField(
            model_name='transinfo',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='transinfo',
            name='img',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='transinfo',
            name='information_validity',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='信息有效期'),
        ),
        migrations.AlterField(
            model_name='transinfo',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='transinfo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='标题'),
        ),
    ]
