# Generated by Django 2.1 on 2019-08-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0013_auto_20190807_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('content', models.TextField(default='', verbose_name='备忘录内容')),
            ],
        ),
    ]
