# Generated by Django 2.1 on 2019-10-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0014_auto_20191014_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='reward_price',
            field=models.FloatField(blank=True, default=0.01, null=True, verbose_name='价格'),
        ),
    ]
