# Generated by Django 2.1 on 2019-08-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0014_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='reward_price',
            field=models.FloatField(default=0, verbose_name='价格'),
        ),
    ]
