# Generated by Django 2.1 on 2019-10-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0015_auto_20191022_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='memo',
            name='m_date',
            field=models.CharField(default='', max_length=64, verbose_name='时间'),
        ),
    ]
