# Generated by Django 2.1 on 2019-08-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0015_auto_20190816_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractinfo',
            name='reward_price',
            field=models.FloatField(default=199, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='investmentdata',
            name='reward_price',
            field=models.FloatField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='reward_price',
            field=models.FloatField(default=199, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='reward_price',
            field=models.FloatField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='transinfo',
            name='reward_price',
            field=models.FloatField(default=199, verbose_name='价格'),
        ),
    ]
