# Generated by Django 2.1 on 2019-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0016_auto_20191030_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户id'),
        ),
    ]
