# Generated by Django 2.1 on 2019-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0016_auto_20190816_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractinfo',
            name='audit_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landinfo',
            name='audit_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transinfo',
            name='audit_state',
            field=models.IntegerField(default=0),
        ),
    ]
