# Generated by Django 2.1 on 2019-08-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0017_auto_20190821_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditOpinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.IntegerField(default=0, verbose_name='资讯id')),
                ('opinion', models.CharField(default='', max_length=255, verbose_name='审核意见')),
                ('source', models.CharField(default='', max_length=8, verbose_name='来源')),
                ('user_id', models.IntegerField(default=0, verbose_name='发布者')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='YaoQing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luyou', models.CharField(default='', max_length=32, verbose_name='路由')),
                ('land_id', models.IntegerField(default=0, verbose_name='资讯id')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='YaoQingRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaoqing_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
