# Generated by Django 2.1 on 2019-11-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0017_memo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinfo',
            name='coordinates',
            field=models.TextField(blank=True, default='', null=True, verbose_name='坐标'),
        ),
    ]
