# Generated by Django 2.1 on 2019-11-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0018_landinfo_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractinfo',
            name='coordinates',
            field=models.TextField(blank=True, default='', null=True, verbose_name='坐标'),
        ),
        migrations.AddField(
            model_name='transinfo',
            name='coordinates',
            field=models.TextField(blank=True, default='', null=True, verbose_name='坐标'),
        ),
    ]
