# Generated by Django 2.1 on 2019-11-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0019_auto_20191107_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractinfo',
            name='pcc',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='省市县坐标'),
        ),
        migrations.AddField(
            model_name='landinfo',
            name='pcc',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='省市县坐标'),
        ),
        migrations.AddField(
            model_name='transinfo',
            name='pcc',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='省市县坐标'),
        ),
    ]
