# Generated by Django 2.1 on 2019-08-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0019_activity_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='yaoqingren',
            field=models.IntegerField(default=0, verbose_name='邀请人id'),
        ),
    ]
