# Generated by Django 2.1 on 2019-08-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0020_collection_yaoqingren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='yaoqingren',
        ),
        migrations.AddField(
            model_name='yaoqing',
            name='yaoqingren',
            field=models.IntegerField(default=0, verbose_name='邀请人id'),
        ),
    ]
