# Generated by Django 2.1 on 2019-08-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0021_auto_20190823_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='img',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='图片'),
        ),
    ]
