# Generated by Django 2.1 on 2019-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0022_auto_20190827_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractinfo',
            name='enterprise_requirements',
            field=models.CharField(default='', max_length=128, verbose_name='产业要求'),
        ),
        migrations.AddField(
            model_name='attractinfo',
            name='img_list',
            field=models.CharField(default='', max_length=256, verbose_name='图集'),
        ),
        migrations.AddField(
            model_name='attractinfo',
            name='industry_requirements',
            field=models.CharField(default='', max_length=128, verbose_name='产业要求'),
        ),
        migrations.AddField(
            model_name='landinfo',
            name='add_amplitude',
            field=models.FloatField(default=0, verbose_name='加价幅度'),
        ),
        migrations.AddField(
            model_name='landinfo',
            name='img_list',
            field=models.CharField(default='', max_length=255, verbose_name='图集'),
        ),
        migrations.AddField(
            model_name='landinfo',
            name='now_progress',
            field=models.CharField(default='', max_length=128, verbose_name='目前进度'),
        ),
        migrations.AddField(
            model_name='landinfo',
            name='special_requirements',
            field=models.CharField(default='', max_length=256, verbose_name='特殊要求'),
        ),
        migrations.AddField(
            model_name='landinfo',
            name='yuji_guapai',
            field=models.CharField(default='', max_length=128, verbose_name='预计挂牌时间'),
        ),
        migrations.AddField(
            model_name='transinfo',
            name='img_list',
            field=models.CharField(default='', max_length=256, verbose_name='图集'),
        ),
        migrations.AddField(
            model_name='transinfo',
            name='information_validity',
            field=models.CharField(default='', max_length=32, verbose_name='信息有效期'),
        ),
    ]
