# Generated by Django 2.1 on 2019-08-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0024_auto_20190827_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='add_amplitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='加价幅度'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='now_progress',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='目前进度'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='special_requirements',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='特殊要求'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='yuji_guapai',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='预计挂牌时间'),
        ),
    ]
