# Generated by Django 2.1 on 2019-08-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0025_auto_20190827_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='add_amplitude',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='加价幅度'),
        ),
    ]
