# Generated by Django 2.1 on 2019-08-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0026_auto_20190828_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractinfo',
            name='enterprise_requirements',
        ),
    ]
