# Generated by Django 2.1 on 2019-08-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0027_remove_attractinfo_enterprise_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractinfo',
            name='house_account',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='住房比'),
        ),
        migrations.AddField(
            model_name='landinfo',
            name='house_account',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='住房比'),
        ),
        migrations.AddField(
            model_name='transinfo',
            name='house_account',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='住房比'),
        ),
    ]
