# Generated by Django 2.1 on 2019-09-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('add_date', models.DateField(verbose_name='添加时间')),
                ('activaty_date', models.DateField(verbose_name='活动时间')),
                ('activaty_place', models.CharField(max_length=300, verbose_name='活动地点')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
