# Generated by Django 2.1 on 2019-09-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=500, verbose_name='消息内容')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(default='', max_length=64, verbose_name='消息标题')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
            ],
        ),
    ]
