# Generated by Django 2.1 on 2019-09-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_systemmessagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('sys_id', models.IntegerField(default=0, verbose_name='推送id')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
