# Generated by Django 2.1 on 2019-09-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_systemread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmessagemodel',
            name='title',
        ),
    ]
