# Generated by Django 2.1 on 2019-09-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_systemmessagemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessagemodel',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='systemread',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
