# Generated by Django 2.1 on 2019-09-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190917_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessagemodel',
            name='sys_type',
            field=models.CharField(default='', max_length=16, verbose_name='类别'),
        ),
    ]
