# Generated by Django 2.1 on 2019-09-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_systemmessagemodel_sys_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessagemodel',
            name='trade_no',
            field=models.CharField(default='1', max_length=32, verbose_name='交易号'),
        ),
    ]
