# Generated by Django 2.1 on 2019-09-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_systemmessagemodel_trade_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LjyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('password', models.CharField(default='', max_length=500, verbose_name='密码')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('login_num', models.IntegerField(default=1, verbose_name='登陆次数')),
            ],
        ),
    ]
