# Generated by Django 2.1 on 2019-10-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_ljyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('first_question', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='问题1')),
                ('second_question', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='问题2')),
                ('third_question', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='问题3')),
                ('fourth_question', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='问题4')),
                ('fifth_question', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='问题5')),
            ],
        ),
    ]
