# Generated by Django 2.1 on 2019-10-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_discern'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegralRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('integral_type', models.IntegerField(default=0, verbose_name='类别')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('integral', models.IntegerField(default=0, verbose_name='获得的积分')),
            ],
        ),
    ]
