# Generated by Django 2.1 on 2019-10-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_integralrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integralrecord',
            name='integral_type',
            field=models.CharField(default='', max_length=16, verbose_name='类别'),
        ),
    ]
