# Generated by Django 2.1 on 2019-10-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20191016_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeiCe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_status', models.IntegerField(default=0, verbose_name='是否已看')),
            ],
        ),
    ]
