# Generated by Django 2.1 on 2019-10-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_neice'),
    ]

    operations = [
        migrations.AddField(
            model_name='neice',
            name='leibie',
            field=models.CharField(default='', max_length=16, verbose_name='类别'),
        ),
    ]
