# Generated by Django 2.1 on 2019-10-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_neice_leibie'),
    ]

    operations = [
        migrations.AddField(
            model_name='discern',
            name='state',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
