# Generated by Django 2.1 on 2019-10-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_discern_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='discern',
            name='fen',
            field=models.IntegerField(default=0, verbose_name='分'),
        ),
    ]
