# Generated by Django 2.1 on 2019-11-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_discern_fen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preview',
            options={},
        ),
        migrations.RemoveField(
            model_name='preview',
            name='activaty_date',
        ),
        migrations.RemoveField(
            model_name='preview',
            name='activaty_place',
        ),
        migrations.RemoveField(
            model_name='preview',
            name='add_date',
        ),
    ]
