# Generated by Django 2.1 on 2019-11-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20191111_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond', models.CharField(default='', max_length=16, verbose_name='纽带')),
                ('record', models.TextField(default='', verbose_name='记录')),
                ('is_read', models.CharField(default='', max_length=64, verbose_name='是否已读')),
            ],
        ),
    ]
