# Generated by Django 2.1 on 2019-11-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_historyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(default=0, verbose_name='客服id')),
                ('y_list', models.TextField(default='', verbose_name='广播列表')),
            ],
        ),
    ]
