# Generated by Django 2.1 on 2019-11-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_userlistmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyrecord',
            name='is_read',
        ),
    ]
